{
 "title": "Django Overview",
 "description": "Django metrics dashboard using korfuri/django-prometheus Prometheus metrics exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(django_http_requests_total_by_method_total, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(django_http_requests_total_by_method_total, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(django_db_new_connections_total, namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total creations per second",
   "type": "timeseries",
   "description": "Total model objects created per second.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(model) (\n    rate(django_model_inserts_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\"}[$__rate_interval])\n    )",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total updates per second",
   "type": "timeseries",
   "description": "Total model objects updated per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(model) (\n    rate(django_model_updates_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\"}[$__rate_interval])\n    )",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total deletes per second",
   "type": "timeseries",
   "description": "Total model objects deleted per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(model) (\n    rate(django_model_deletes_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\"}[$__rate_interval])\n    )",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_requests_total_by_view_transport_method_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_view_method_total{job=~\"$job\", instance=~\"$instance\", status=~\"2.+\",namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_view_method_total{job=~\"$job\", instance=~\"$instance\", status=~\"4.+\",namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_view_method_total{job=~\"$job\", instance=~\"$instance\", status=~\"5.+\",namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Requests per seconds, aggregated over HTTP method, and view.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, view) (\n    rate(django_http_requests_total_by_view_transport_method_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])\n    )",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{job=~\"$job\", instance=~\"$instance\", namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_sum{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Total error rate for all views. Errors are considered responses with 5xx http status code.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(\n    rate(django_http_responses_total_by_status_view_method_total{job=~\"$job\", instance=~\"$instance\", status=~\"5..\", namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])\n    ) or vector(0)) /\nsum(\n    rate(django_http_responses_total_by_status_view_method_total{job=~\"$job\", instance=~\"$instance\", namespace=~\"\", app=~\"^$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])\n    )",
     "legendFormat": "Error rate"
    }
   ]
  }
 ]
}